# Site settings
title: Linux Users Group @ UTD
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We are a student organization devoted to the teaching and advocacy of Linux,
  open source, and free software of all kinds. We welcome anyone and everyone
  from the Linux, Unix, BSD, and macOS realms, so come join us! All of our
  meetings are open to the public.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lug.utdallas.edu/" # the base hostname & protocol for your site
twitter_username: utdlug
github_username:  utdlug

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/feed/p:num"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
